apiVersion: spec.keptn.sh/0.2.2
kind: "Shipyard"
metadata:
  name: "Project to demo Jira integrations"
spec:
  stages:
    - name: "production"
      sequences:
      - name: "problemNotification"
        tasks:
        - name: "createJira"
        - name: "evaluation"
          properties:
            timeframe: "5m"
        - name: "updateJira"
