apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.createJira.finished
      requests:
        - "curl --request POST --data '{  \"note\": \"webhook.site
          subscription\",\t\"type\": \"{{.type}}\",\t\"shkeptncontext\":
          \"{{.shkeptncontext}}\",\t\"id\": \"{{.id}}\",    \"data\":
          {        \"project\": \"{{.data.project}}\",        \"service\":
          \"{{.data.service}}\",        \"stage\":
          \"{{.data.stage}}\",        \"bridge\":
          \"{{.data.bridge}}\",        \"dynatraceProblem\":
          {            \"ProblemID\":
          \"{{.data.dynatraceProblem.ProblemID}}\",            \"Tags\":
          \"{{.data.dynatraceProblem.Tags}}\",            \"ProblemTitle\":
          \"{{.data.dynatraceProblem.ProblemTitle}}\",            \"ProblemURL\
          \": \"{{.data.dynatraceProblem.ProblemURL}}\",            \"State\":
          \"{{.data.dynatraceProblem.State}}\",            \"PID\":\"{{.data.dy\
          natraceProblem.PID}}\",            \"ImpactedEntity\":\"{{webhookData\
          .data.dynatraceProblem.ImpactedEntity}}\"        },        \"createJi\
          ra\": {            \"url\": \"{{ .data.createJira.url
          }}\",            \"key\": \"{{ .data.createJira.key
          }}\",            \"summary\": \"{{ .data.createJira.summary
          }}\"        },    }}'
          https://webhook.site/2be34b4b-8a90-47cd-ba9f-a3e237e90765"
      subscriptionID: 6a0241fd-f112-4db3-8e1f-3cf9abc5213b
    - type: sh.keptn.event.createJira.triggered
      requests:
        - "curl --request POST --data '{  \"note\": \"webhook.site
          subscription\",{    \"type\": \"{{.type}}\",    \"shkeptncontext\":
          \"{{.shkeptncontext}}\",\t\"id\": \"{{.id}}\",    \"data\":
          {        \"project\": \"{{.data.project}}\",        \"service\":
          \"{{.data.service}}\",        \"stage\":
          \"{{.data.stage}}\",        \"bridge\":
          \"{{.env.secret_bridge_url}}/project/{{.data.project}}/sequence/{{.sh\
          keptncontext}}\",        \"dynatraceProblem\":
          {            \"ProblemID\":
          \"{{.data.dynatraceProblem.ProblemID}}\",            \"Tags\":
          \"{{.data.dynatraceProblem.Tags}}\",            \"ProblemTitle\":
          \"{{.data.dynatraceProblem.ProblemTitle}}\",            \"ProblemURL\
          \": \"{{.data.dynatraceProblem.ProblemURL}}\",            \"State\":
          \"{{.data.dynatraceProblem.State}}\",            \"PID\":\"{{.data.dy\
          natraceProblem.PID}}\",            \"ImpactedEntity\":\"{{.data.dynat\
          raceProblem.ImpactedEntity}}\"        }    }}'
          https://webhook.site/2be34b4b-8a90-47cd-ba9f-a3e237e90765"
      envFrom:
        - name: secret_bridge_url
          secretRef:
            name: bridge
            key: url
      subscriptionID: 9f9782d2-c1da-4f11-a2a8-de9c20bb02c4
    - type: sh.keptn.event.createJira.triggered
      requests:
        - "curl --header 'Content-type: application/json' --request POST --data
          '{{    \"type\": \"{{.type}}\",    \"shkeptncontext\":
          \"{{.shkeptncontext}}\",\t\"id\": \"{{.id}}\",    \"data\":
          {        \"project\": \"{{.data.project}}\",        \"service\":
          \"{{.data.service}}\",        \"stage\":
          \"{{.data.stage}}\",        \"bridge\":
          \"{{.env.secret_bridge_url}}/project/{{.data.project}}/sequence/{{.sh\
          keptncontext}}\",        \"dynatraceProblem\":
          {            \"ProblemID\":
          \"{{.data.dynatraceProblem.ProblemID}}\",            \"Tags\":
          \"{{.data.dynatraceProblem.Tags}}\",            \"ProblemTitle\":
          \"{{.data.dynatraceProblem.ProblemTitle}}\",            \"ProblemURL\
          \": \"{{.data.dynatraceProblem.ProblemURL}}\",            \"State\":
          \"{{.data.dynatraceProblem.State}}\",            \"PID\":\"{{.data.dy\
          natraceProblem.PID}}\",            \"ImpactedEntity\":\"{{.data.dynat\
          raceProblem.ImpactedEntity}}\"        }    }}'
          https://automation.atlassian.com/pro/hooks/{{.env.secret_jira_create}\
          }"
      envFrom:
        - name: secret_jira_create
          secretRef:
            name: jira
            key: create
        - name: secret_bridge_url
          secretRef:
            name: bridge
            key: url
      subscriptionID: b9b83b3f-64d8-464d-b303-bfe54d799e60
