apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.update-jira.triggered
      requests:
        - "curl --request POST --data '{\t\"type\": \"{{.type}}\",\t\"project\":
          \"{{.data.project}}\",\t\"service\":
          \"{{.data.service}}\",\t\"stage\":
          \"{{.data.stage}}\",\t\"shkeptncontext\":
          \"{{.shkeptncontext}}\",\t\"id\": \"{{.id}}\",\t\"create-jira\":
          {\t\t\"url\": \"{{ (index .data \"create-jira\").url }}\",\t\t\"key\":
          \"{{ (index .data \"create-jira\").key}}\",\t\t\"summary\": \"{{
          (index .data \"create-jira\").summary}}\"\t},\t\"evaluation\":
          {\t\t\"result\": \"{{.data.evaluation.result}}\",\t\t\"score\":
          {{.data.evaluation.score}}\t}}'
          https://automation.atlassian.com/pro/hooks/{{.env.secret_jira_update}\
          }"
      envFrom:
        - name: secret_jira_update
          secretRef:
            name: jira
            key: update
      subscriptionID: 3d5fa8e4-d5da-4d65-80c3-abbe652a294e
    - type: sh.keptn.event.createJira.finished
      requests:
        - "curl --request POST --data '{    \"note\": \"from the create-jira
          finished webhook.site subscription\",    \"type\":
          \"{{.type}}\",    \"data\": {        \"project\":
          \"{{.data.project}}\",        \"service\":
          \"{{.data.service}}\",        \"stage\":
          \"{{.data.stage}}\",        \"bridge\":
          \"{{.env.secret_bridge_url}}/project/{{.data.project}}/sequence/{{.sh\
          keptncontext}}\",        \"dynatraceProblem\":
          {            \"ProblemID\":
          \"{{.data.dynatraceProblem.ProblemID}}\",            \"Tags\":
          \"{{.data.dynatraceProblem.Tags}}\",            \"ProblemTitle\":
          \"{{.data.dynatraceProblem.ProblemTitle}}\",            \"ProblemURL\
          \": \"{{.data.dynatraceProblem.ProblemURL}}\",            \"State\":
          \"{{.data.dynatraceProblem.State}}\",            \"PID\":\"{{.data.dy\
          natraceProblem.PID}}\",            \"ImpactedEntities\":\"{{.data.dyn\
          atraceProblem.ImpactedEntities}}\",            \"ImpactedEntity\":{{.\
          data.dynatraceProblem.ImpactedEntity}}        }    }}'
          https://webhook.site/2be34b4b-8a90-47cd-ba9f-a3e237e90765"
      envFrom:
        - name: secret_bridge_url
          secretRef:
            name: bridge
            key: url
      subscriptionID: 6a0241fd-f112-4db3-8e1f-3cf9abc5213b
    - type: sh.keptn.event.createJira.triggered
      requests:
        - "curl --header 'Content-type: application/json' --request POST --data
          '{    \"type\": \"{{.type}}\",    \"shkeptncontext\":
          \"{{.shkeptncontext}}\",\t\"id\": \"{{.id}}\",    \"data\":
          {        \"project\": \"{{.data.project}}\",        \"service\":
          \"{{.data.service}}\",        \"stage\":
          \"{{.data.stage}}\",        \"bridge\":
          \"{{.env.secret_bridge_url}}/project/{{.data.project}}/sequence/{{.sh\
          keptncontext}}\",        \"dynatraceProblem\":
          {            \"ProblemID\":
          \"{{.data.dynatraceProblem.ProblemID}}\",            \"Tags\":
          \"{{.data.dynatraceProblem.Tags}}\",            \"ProblemTitle\":
          \"{{.data.dynatraceProblem.ProblemTitle}}\",            \"ProblemURL\
          \": \"{{.data.dynatraceProblem.ProblemURL}}\",            \"State\":
          \"{{.data.dynatraceProblem.State}}\",            \"PID\":\"{{.data.dy\
          natraceProblem.PID}}\",            \"ImpactedEntities\":\"{{.data.dyn\
          atraceProblem.ImpactedEntities}}\",            \"ImpactedEntity\":{{.\
          data.dynatraceProblem.ImpactedEntity}}        }    }}'
          https://automation.atlassian.com/pro/hooks/{{.env.secret_jira_create}\
          }"
      envFrom:
        - name: secret_jira_create
          secretRef:
            name: jira
            key: create
        - name: secret_bridge_url
          secretRef:
            name: bridge
            key: url
      subscriptionID: b9b83b3f-64d8-464d-b303-bfe54d799e60
